package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdBuyOrderDetails;

public class XxdBuyOrderDetailsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_buy_order_details
     *
     * @mbggenerated
     */
    public String insertSelective(XxdBuyOrderDetails record) {
        BEGIN();
        INSERT_INTO("xxd_buy_order_details");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getPrice() != null) {
            VALUES("price", "#{price,jdbcType=INTEGER}");
        }
        
        if (record.getBuyOrderId() != null) {
            VALUES("buy_order_id", "#{buyOrderId,jdbcType=INTEGER}");
        }
        
        if (record.getNum() != null) {
            VALUES("num", "#{num,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsId() != null) {
            VALUES("goods_id", "#{goodsId,jdbcType=INTEGER}");
        }
        
        if(record.getSta() != null) {
        	VALUES("sta", "#{sta,jdbcType=SMALLINT}");
        }
        
        if(record.getTime() != null) {
        	VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_buy_order_details
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdBuyOrderDetails record) {
        BEGIN();
        UPDATE("xxd_buy_order_details");
        
        if (record.getPrice() != null) {
            SET("price = #{price,jdbcType=INTEGER}");
        }
        
        if (record.getBuyOrderId() != null) {
            SET("buy_order_id = #{buyOrderId,jdbcType=INTEGER}");
        }
        
        if (record.getNum() != null) {
            SET("num = #{num,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsId() != null) {
            SET("goods_id = #{goodsId,jdbcType=INTEGER}");
        }
        
        if(record.getSta() != null) {
        	SET("sta = #{sta,jdbcType=SMALLINT}");
        }
        
        if(record.getTime() != null) {
        	SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}