package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdBuyOrder;

public class XxdBuyOrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_buy_order
     *
     * @mbggenerated
     */
    public String insertSelective(XxdBuyOrder record) {
        BEGIN();
        INSERT_INTO("xxd_buy_order");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalPrice() != null) {
            VALUES("total_price", "#{totalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAddrId() != null) {
            VALUES("addr_id", "#{addrId,jdbcType=INTEGER}");
        }
        
        if (record.getFreightId() != null) {
            VALUES("freight_id", "#{freightId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            VALUES("order_id", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyId() != null) {
            VALUES("buy_id", "#{buyId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            VALUES("sta", "#{sta,jdbcType=SMALLINT}");
        }
        
        if(record.getType() != null) {
        	VALUES("type", "#{type,jdbcType=SMALLINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_buy_order
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdBuyOrder record) {
        BEGIN();
        UPDATE("xxd_buy_order");
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        if (record.getTotalPrice() != null) {
            SET("total_price = #{totalPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getAddrId() != null) {
            SET("addr_id = #{addrId,jdbcType=INTEGER}");
        }
        
        if (record.getFreightId() != null) {
            SET("freight_id = #{freightId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            SET("order_id = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getBuyId() != null) {
            SET("buy_id = #{buyId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            SET("sta = #{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=SMALLINT}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}