package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdComplain;

public class XxdComplainSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    public String insertSelective(XxdComplain record) {
        BEGIN();
        INSERT_INTO("xxd_complain");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getComplainUid() != null) {
            VALUES("complain_uid", "#{complainUid,jdbcType=INTEGER}");
        }
        
        if (record.getReason() != null) {
            VALUES("reason", "#{reason,jdbcType=SMALLINT}");
        }
        
        if (record.getSaveDir() != null) {
            VALUES("save_dir", "#{saveDir,jdbcType=VARCHAR}");
        }
        
        if (record.getSta() != null) {
            VALUES("sta", "#{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getResultDesc() != null) {
            VALUES("result_desc", "#{resultDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdComplain record) {
        BEGIN();
        UPDATE("xxd_complain");
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getComplainUid() != null) {
            SET("complain_uid = #{complainUid,jdbcType=INTEGER}");
        }
        
        if (record.getReason() != null) {
            SET("reason = #{reason,jdbcType=SMALLINT}");
        }
        
        if (record.getSaveDir() != null) {
            SET("save_dir = #{saveDir,jdbcType=VARCHAR}");
        }
        
        if (record.getSta() != null) {
            SET("sta = #{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getResultDesc() != null) {
            SET("result_desc = #{resultDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}