package com.xxd.mappers;

import com.xxd.models.XxdComplain;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdComplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_complain",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_complain (id, uid, ",
        "complain_uid, reason, ",
        "save_dir, sta, result_desc, ",
        "time)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{complainUid,jdbcType=INTEGER}, #{reason,jdbcType=SMALLINT}, ",
        "#{saveDir,jdbcType=VARCHAR}, #{sta,jdbcType=SMALLINT}, #{resultDesc,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=VARCHAR})"
    })
    int insert(XxdComplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdComplainSqlProvider.class, method="insertSelective")
    int insertSelective(XxdComplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, uid, complain_uid, reason, save_dir, sta, result_desc, time",
        "from xxd_complain",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="complain_uid", property="complainUid", jdbcType=JdbcType.INTEGER),
        @Result(column="reason", property="reason", jdbcType=JdbcType.SMALLINT),
        @Result(column="save_dir", property="saveDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="sta", property="sta", jdbcType=JdbcType.SMALLINT),
        @Result(column="result_desc", property="resultDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR)
    })
    XxdComplain selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, uid, complain_uid, reason, save_dir, sta, result_desc, time",
        "from xxd_complain"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="complain_uid", property="complainUid", jdbcType=JdbcType.INTEGER),
        @Result(column="reason", property="reason", jdbcType=JdbcType.SMALLINT),
        @Result(column="save_dir", property="saveDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="sta", property="sta", jdbcType=JdbcType.SMALLINT),
        @Result(column="result_desc", property="resultDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR)
    })
    ArrayList<XxdComplain> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdComplainSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdComplain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_complain
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_complain",
        "set uid = #{uid,jdbcType=INTEGER},",
          "complain_uid = #{complainUid,jdbcType=INTEGER},",
          "reason = #{reason,jdbcType=SMALLINT},",
          "save_dir = #{saveDir,jdbcType=VARCHAR},",
          "sta = #{sta,jdbcType=SMALLINT},",
          "result_desc = #{resultDesc,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdComplain record);
}