package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdGroup;

public class XxdGroupSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_group
     *
     * @mbggenerated
     */
    public String insertSelective(XxdGroup record) {
        BEGIN();
        INSERT_INTO("xxd_group");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsGroupId() != null) {
            VALUES("goods_group_id", "#{goodsGroupId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            VALUES("sta", "#{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getNo() != null) {
            VALUES("no", "#{no,jdbcType=VARCHAR}");
        }
        
        if (record.getNums() != null) {
            VALUES("nums", "#{nums,jdbcType=SMALLINT}");
        }
        
        if (record.getStartTime() != null) {
            VALUES("start_time", "#{startTime,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            VALUES("end_time", "#{endTime,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_group
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdGroup record) {
        BEGIN();
        UPDATE("xxd_group");
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsGroupId() != null) {
            SET("goods_group_id = #{goodsGroupId,jdbcType=INTEGER}");
        }
        
        if (record.getSta() != null) {
            SET("sta = #{sta,jdbcType=SMALLINT}");
        }
        
        if (record.getNo() != null) {
            SET("no = #{no,jdbcType=VARCHAR}");
        }
        
        if (record.getNums() != null) {
            SET("nums = #{nums,jdbcType=SMALLINT}");
        }
        
        if (record.getStartTime() != null) {
            SET("start_time = #{startTime,jdbcType=VARCHAR}");
        }
        
        if (record.getEndTime() != null) {
            SET("end_time = #{endTime,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}