package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdGoodsProductPackage;

public class XxdGoodsProductPackageSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    public String insertSelective(XxdGoodsProductPackage record) {
        BEGIN();
        INSERT_INTO("xxd_goods_product_package");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketPrice() != null) {
            VALUES("market_price", "#{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPrice() != null) {
            VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getNum() != null) {
            VALUES("num", "#{num,jdbcType=INTEGER}");
        }
        
        if (record.getSendPosition() != null) {
            VALUES("send_position", "#{sendPosition,jdbcType=VARCHAR}");
        }
        
        if (record.getImgFontDir() != null) {
            VALUES("img_font_dir", "#{imgFontDir,jdbcType=VARCHAR}");
        }
        
        if (record.getShowImgDir() != null) {
            VALUES("show_img_dir", "#{showImgDir,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnershipLeaderId() != null) {
            VALUES("ownership_leader_id", "#{ownershipLeaderId,jdbcType=INTEGER}");
        }
        
        if (record.getGroundingSta() != null) {
            VALUES("grounding_sta", "#{groundingSta,jdbcType=SMALLINT}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=SMALLINT}");
        }
        
        if (record.getClassId() != null) {
            VALUES("class_id", "#{classId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdGoodsProductPackage record) {
        BEGIN();
        UPDATE("xxd_goods_product_package");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketPrice() != null) {
            SET("market_price = #{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getPrice() != null) {
            SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getNum() != null) {
            SET("num = #{num,jdbcType=INTEGER}");
        }
        
        if (record.getSendPosition() != null) {
            SET("send_position = #{sendPosition,jdbcType=VARCHAR}");
        }
        
        if (record.getImgFontDir() != null) {
            SET("img_font_dir = #{imgFontDir,jdbcType=VARCHAR}");
        }
        
        if (record.getShowImgDir() != null) {
            SET("show_img_dir = #{showImgDir,jdbcType=VARCHAR}");
        }
        
        if (record.getOwnershipLeaderId() != null) {
            SET("ownership_leader_id = #{ownershipLeaderId,jdbcType=INTEGER}");
        }
        
        if (record.getGroundingSta() != null) {
            SET("grounding_sta = #{groundingSta,jdbcType=SMALLINT}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=SMALLINT}");
        }
        
        if (record.getClassId() != null) {
            SET("class_id = #{classId,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}