package com.xxd.mappers;

import com.xxd.models.XxdGoodsPrice;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_price",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_price (id, format_name, ",
        "market_price, leader_price, ",
        "member_price, remark, ",
        "goods_id, num, img, price)",
        "values (#{id,jdbcType=INTEGER}, #{formatName,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{leaderPrice,jdbcType=DECIMAL}, ",
        "#{memberPrice,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, ",
        "#{goodsId,jdbcType=INTEGER}, #{num,jdbcType=INTEGER}, ",
        "#{img,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL})"
    })
    int insert(XxdGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsPriceSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, format_name, market_price, leader_price, member_price, remark, goods_id, num, img, price",
        "from xxd_goods_price",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="format_name", property="formatName", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="leader_price", property="leaderPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="member_price", property="memberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL)
    })
    XxdGoodsPrice selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, format_name, market_price, leader_price, member_price, remark, goods_id, num, img, price",
        "from xxd_goods_price"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="format_name", property="formatName", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="leader_price", property="leaderPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="member_price", property="memberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL)
    })
    ArrayList<XxdGoodsPrice> selectAll();
    
    @Select({
        "select",
        "id, format_name, market_price, leader_price, member_price, remark, goods_id, num, img, price",
        "from xxd_goods_price",
        "where goods_id = #{goods_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="format_name", property="formatName", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="leader_price", property="leaderPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="member_price", property="memberPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL)
    })
    ArrayList<XxdGoodsPrice> selectAllByGoodsId(Integer goods_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsPriceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_price",
        "set format_name = #{formatName,jdbcType=VARCHAR},",
          "market_price = #{marketPrice,jdbcType=DECIMAL},",
          "leader_price = #{leaderPrice,jdbcType=DECIMAL},",
          "member_price = #{memberPrice,jdbcType=DECIMAL},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=INTEGER}",
          "num = #{num,jdbcType=INTEGER}",
          "img = #{img,jdbcType=VARCHAR}",
          "price = #{price,jdbcType=DECIMAL}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsPrice record);
}