package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdGoodsPrice;

public class XxdGoodsPriceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    public String insertSelective(XxdGoodsPrice record) {
        BEGIN();
        INSERT_INTO("xxd_goods_price");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getFormatName() != null) {
            VALUES("format_name", "#{formatName,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketPrice() != null) {
            VALUES("market_price", "#{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getLeaderPrice() != null) {
            VALUES("leader_price", "#{leaderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getMemberPrice() != null) {
            VALUES("member_price", "#{memberPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getRemark() != null) {
            VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            VALUES("goods_id", "#{goodsId,jdbcType=INTEGER}");
        }
        
        if(record.getNum() != null) {
        	VALUES("num", "#{num,jdbcType=INTEGER}");
        }
        
        if(record.getImg() != null) {
        	VALUES("img", "#{img,jdbcType=VARCHAR}");
        }
        
        if(record.getPrice() != null) {
        	VALUES("price", "#{price,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_price
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdGoodsPrice record) {
        BEGIN();
        UPDATE("xxd_goods_price");
        
        if (record.getFormatName() != null) {
            SET("format_name = #{formatName,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketPrice() != null) {
            SET("market_price = #{marketPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getLeaderPrice() != null) {
            SET("leader_price = #{leaderPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getMemberPrice() != null) {
            SET("member_price = #{memberPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getRemark() != null) {
            SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsId() != null) {
            SET("goods_id = #{goodsId,jdbcType=INTEGER}");
        }
        
        if(record.getNum() != null) {
        	SET("num = #{num,jdbcType=INTEGER}");
        }
        
        if(record.getImg() != null) {
        	SET("img = #{img,jdbcType=VARCHAR}");
        }
        
        if(record.getPrice() != null) {
        	SET("price = #{price,jdbcType=DECIMAL}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}