package com.xxd.mappers;

import com.xxd.models.XxdGoodsClass;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_class",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_class (id, name, ",
        "parent_id, level)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=INTEGER}, #{level,jdbcType=SMALLINT})"
    })
    int insert(XxdGoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsClassSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, parent_id, level",
        "from xxd_goods_class",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.SMALLINT)
    })
    XxdGoodsClass selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, name, parent_id, level",
        "from xxd_goods_class",
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.SMALLINT)
    })
    ArrayList<XxdGoodsClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsClassSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_class
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_class",
        "set name = #{name,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "level = #{level,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsClass record);
}