package com.xxd.mappers;

import com.xxd.models.XxdGoodsProductPackage;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsProductPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_product_package",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_product_package (id, name, ",
        "market_price, price, ",
        "num, send_position, ",
        "img_font_dir, show_img_dir, ",
        "ownership_leader_id, grounding_sta, ",
        "type, class_id)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{marketPrice,jdbcType=DECIMAL}, #{price,jdbcType=DECIMAL}, ",
        "#{num,jdbcType=INTEGER}, #{sendPosition,jdbcType=VARCHAR}, ",
        "#{imgFontDir,jdbcType=VARCHAR}, #{showImgDir,jdbcType=VARCHAR}, ",
        "#{ownershipLeaderId,jdbcType=INTEGER}, #{groundingSta,jdbcType=SMALLINT}, ",
        "#{type,jdbcType=SMALLINT}, #{classId,jdbcType=INTEGER})"
    })
    int insert(XxdGoodsProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsProductPackageSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, market_price, price, num, send_position, img_font_dir, show_img_dir, ",
        "ownership_leader_id, grounding_sta, type, class_id",
        "from xxd_goods_product_package",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="send_position", property="sendPosition", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_font_dir", property="imgFontDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="show_img_dir", property="showImgDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="ownership_leader_id", property="ownershipLeaderId", jdbcType=JdbcType.INTEGER),
        @Result(column="grounding_sta", property="groundingSta", jdbcType=JdbcType.SMALLINT),
        @Result(column="type", property="type", jdbcType=JdbcType.SMALLINT),
        @Result(column="class_id", property="classId", jdbcType=JdbcType.INTEGER)
    })
    XxdGoodsProductPackage selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "xgpp.id id, xgpp.name name, xgpp.market_price market_price, xgpp.price price, xgpp.num num, xgpp.send_position send_position, xgpp.img_font_dir img_font_dir, xgpp.show_img_dir show_img_dir, ",
        "xgpp.ownership_leader_id ownership_leader_id, xgpp.grounding_sta grounding_sta, xgpp.type type",
        "from xxd_goods_product_package xgpp",
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="market_price", property="marketPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="send_position", property="sendPosition", jdbcType=JdbcType.VARCHAR),
        @Result(column="img_font_dir", property="imgFontDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="show_img_dir", property="showImgDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="ownership_leader_id", property="ownershipLeaderId", jdbcType=JdbcType.INTEGER),
        @Result(column="grounding_sta", property="groundingSta", jdbcType=JdbcType.SMALLINT),
        @Result(column="type", property="type", jdbcType=JdbcType.SMALLINT)
    })
    ArrayList<XxdGoodsProductPackage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsProductPackageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_product_package
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_product_package",
        "set name = #{name,jdbcType=VARCHAR},",
          "market_price = #{marketPrice,jdbcType=DECIMAL},",
          "price = #{price,jdbcType=DECIMAL},",
          "num = #{num,jdbcType=INTEGER},",
          "send_position = #{sendPosition,jdbcType=VARCHAR},",
          "img_font_dir = #{imgFontDir,jdbcType=VARCHAR},",
          "show_img_dir = #{showImgDir,jdbcType=VARCHAR},",
          "ownership_leader_id = #{ownershipLeaderId,jdbcType=INTEGER},",
          "grounding_sta = #{groundingSta,jdbcType=SMALLINT},",
          "type = #{type,jdbcType=SMALLINT},",
          "class_id = #{classId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsProductPackage record);
}