package com.xxd.mappers;

import com.xxd.models.XxdGoodsParametric;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdGoodsParametricMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_goods_parametric",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_goods_parametric (id, name, ",
        "value, goods_id, ",
        "sort_no)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{value,jdbcType=VARCHAR}, #{goodsId,jdbcType=INTEGER}, ",
        "#{sortNo,jdbcType=SMALLINT})"
    })
    int insert(XxdGoodsParametric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdGoodsParametricSqlProvider.class, method="insertSelective")
    int insertSelective(XxdGoodsParametric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, value, goods_id, sort_no",
        "from xxd_goods_parametric",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_no", property="sortNo", jdbcType=JdbcType.SMALLINT)
    })
    XxdGoodsParametric selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, name, value, goods_id, sort_no",
        "from xxd_goods_parametric",
        "where goods_id = #{goods_id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR),
        @Result(column="goods_id", property="goodsId", jdbcType=JdbcType.INTEGER),
        @Result(column="sort_no", property="sortNo", jdbcType=JdbcType.SMALLINT)
    })
    ArrayList<XxdGoodsParametric> selectByGoodsId(Integer goods_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdGoodsParametricSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdGoodsParametric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_goods_parametric
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_goods_parametric",
        "set name = #{name,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR},",
          "goods_id = #{goodsId,jdbcType=INTEGER},",
          "sort_no = #{sortNo,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdGoodsParametric record);
}