package com.xxd.mappers;

import com.xxd.models.XxdHopeBuy;
import com.xxd.models.XxdUserHopeBuy;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdHopeBuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_hope_buy",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_hope_buy (id, contents, ",
        "goodsImg, uid)",
        "values (#{id,jdbcType=INTEGER}, #{contents,jdbcType=VARCHAR}, ",
        "#{goodsimg,jdbcType=VARCHAR}, #{uid,jdbcType=INTEGER})"
    })
    int insert(XxdHopeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdHopeBuySqlProvider.class, method="insertSelective")
    int insertSelective(XxdHopeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, contents, goodsImg, uid",
        "from xxd_hope_buy",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contents", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsImg", property="goodsimg", jdbcType=JdbcType.VARCHAR),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER)
    })
    XxdHopeBuy selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "xhb.*,",
        "xu.name",
        "from xxd_hope_buy xhb",
        "left join xxd_user xu on xhb.uid = xu.uid"
      
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="contents", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsImg", property="goodsImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER)
    })
    ArrayList<XxdUserHopeBuy> selectAllUserHopeBuy();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdHopeBuySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdHopeBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_hope_buy
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_hope_buy",
        "set contents = #{contents,jdbcType=VARCHAR},",
          "goodsImg = #{goodsimg,jdbcType=VARCHAR},",
          "uid = #{uid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdHopeBuy record);
}