package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdIntegration;

public class XxdIntegrationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_integration
     *
     * @mbggenerated
     */
    public String insertSelective(XxdIntegration record) {
        BEGIN();
        INSERT_INTO("xxd_integration");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getIntegration() != null) {
            VALUES("integration", "#{integration,jdbcType=DECIMAL}");
        }
        
        if (record.getAbled() != null) {
            VALUES("abled", "#{abled,jdbcType=DECIMAL}");
        }
        
        if (record.getDisabled() != null) {
            VALUES("disabled", "#{disabled,jdbcType=DECIMAL}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_integration
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdIntegration record) {
        BEGIN();
        UPDATE("xxd_integration");
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getIntegration() != null) {
            SET("integration = #{integration,jdbcType=DECIMAL}");
        }
        
        if (record.getAbled() != null) {
            SET("abled = #{abled,jdbcType=DECIMAL}");
        }
        
        if (record.getDisabled() != null) {
            SET("disabled = #{disabled,jdbcType=DECIMAL}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}