package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdOrderExpressNo;

public class XxdOrderExpressNoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_order_express_no
     *
     * @mbggenerated
     */
    public String insertSelective(XxdOrderExpressNo record) {
        BEGIN();
        INSERT_INTO("xxd_order_express_no");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            VALUES("order_id", "#{orderId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderNo() != null) {
            VALUES("order_no", "#{orderNo,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderUserId() != null) {
            VALUES("order_user_id", "#{orderUserId,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_order_express_no
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdOrderExpressNo record) {
        BEGIN();
        UPDATE("xxd_order_express_no");
        
        if (record.getOrderId() != null) {
            SET("order_id = #{orderId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderNo() != null) {
            SET("order_no = #{orderNo,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderUserId() != null) {
            SET("order_user_id = #{orderUserId,jdbcType=INTEGER}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}