package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdProductPackageOrder;

public class XxdProductPackageOrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    public String insertSelective(XxdProductPackageOrder record) {
        BEGIN();
        INSERT_INTO("xxd_product_package_order");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getBuyOrderId() != null) {
            VALUES("buy_order_id", "#{buyOrderId,jdbcType=INTEGER}");
        }
        
        if (record.getOwnerOrderId() != null) {
            VALUES("owner_order_id", "#{ownerOrderId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdProductPackageOrder record) {
        BEGIN();
        UPDATE("xxd_product_package_order");
        
        if (record.getBuyOrderId() != null) {
            SET("buy_order_id = #{buyOrderId,jdbcType=INTEGER}");
        }
        
        if (record.getOwnerOrderId() != null) {
            SET("owner_order_id = #{ownerOrderId,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}