package com.xxd.mappers;

import com.xxd.models.XxdProductPackageOrder;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdProductPackageOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_product_package_order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_product_package_order (id, buy_order_id, ",
        "owner_order_id)",
        "values (#{id,jdbcType=INTEGER}, #{buyOrderId,jdbcType=INTEGER}, ",
        "#{ownerOrderId,jdbcType=INTEGER})"
    })
    int insert(XxdProductPackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdProductPackageOrderSqlProvider.class, method="insertSelective")
    int insertSelective(XxdProductPackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, buy_order_id, owner_order_id",
        "from xxd_product_package_order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="buy_order_id", property="buyOrderId", jdbcType=JdbcType.INTEGER),
        @Result(column="owner_order_id", property="ownerOrderId", jdbcType=JdbcType.INTEGER)
    })
    XxdProductPackageOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdProductPackageOrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdProductPackageOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_product_package_order
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_product_package_order",
        "set buy_order_id = #{buyOrderId,jdbcType=INTEGER},",
          "owner_order_id = #{ownerOrderId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdProductPackageOrder record);
}