package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdPowerGroup;

public class XxdPowerGroupSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_power_group
     *
     * @mbggenerated
     */
    public String insertSelective(XxdPowerGroup record) {
        BEGIN();
        INSERT_INTO("xxd_power_group");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIsAbled() != null) {
            VALUES("is_abled", "#{isAbled,jdbcType=SMALLINT}");
        }
        
        if (record.getPowers() != null) {
            VALUES("powers", "#{powers,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUid() != null) {
            VALUES("create_uid", "#{createUid,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("create_time", "#{createTime,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_power_group
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdPowerGroup record) {
        BEGIN();
        UPDATE("xxd_power_group");
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getIsAbled() != null) {
            SET("is_abled = #{isAbled,jdbcType=SMALLINT}");
        }
        
        if (record.getPowers() != null) {
            SET("powers = #{powers,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateUid() != null) {
            SET("create_uid = #{createUid,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            SET("create_time = #{createTime,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}