package com.xxd.mappers;

import com.xxd.models.XxdSuggestion;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdSuggestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_suggestion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_suggestion (id, time, ",
        "content, save_dir, ",
        "is_read, uid)",
        "values (#{id,jdbcType=INTEGER}, #{time,jdbcType=VARCHAR}, ",
        "#{content,jdbcType=VARCHAR}, #{saveDir,jdbcType=VARCHAR}, ",
        "#{isRead,jdbcType=SMALLINT}, #{uid,jdbcType=INTEGER})"
    })
    int insert(XxdSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdSuggestionSqlProvider.class, method="insertSelective")
    int insertSelective(XxdSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, time, content, save_dir, is_read, uid",
        "from xxd_suggestion",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="save_dir", property="saveDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_read", property="isRead", jdbcType=JdbcType.SMALLINT),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER)
    })
    XxdSuggestion selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, time, content, save_dir, is_read, uid",
        "from xxd_suggestion"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="save_dir", property="saveDir", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_read", property="isRead", jdbcType=JdbcType.SMALLINT),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER)
    })
    ArrayList<XxdSuggestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdSuggestionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdSuggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_suggestion
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_suggestion",
        "set time = #{time,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "save_dir = #{saveDir,jdbcType=VARCHAR},",
          "is_read = #{isRead,jdbcType=SMALLINT},",
          "uid = #{uid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdSuggestion record);
}