package com.xxd.mappers;

import com.xxd.models.XxdUserPower;

import java.util.ArrayList;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface XxdUserPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xxd_user_power",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xxd_user_power (id, uid, ",
        "powers, power_group_id)",
        "values (#{id,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER}, ",
        "#{powers,jdbcType=VARCHAR}, #{powerGroupId,jdbcType=INTEGER})"
    })
    int insert(XxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @InsertProvider(type=XxdUserPowerSqlProvider.class, method="insertSelective")
    int insertSelective(XxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, uid, powers, power_group_id",
        "from xxd_user_power",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="powers", property="powers", jdbcType=JdbcType.VARCHAR),
        @Result(column="power_group_id", property="powerGroupId", jdbcType=JdbcType.INTEGER)
    })
    XxdUserPower selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, uid, powers, (case when power_group_id is null then 0 else power_group_id end) power_group_id",
        "from xxd_user_power",
        "where uid = #{uid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="powers", property="powers", jdbcType=JdbcType.VARCHAR),
        @Result(column="power_group_id", property="powerGroupId", jdbcType=JdbcType.INTEGER)
    })
    XxdUserPower selectByuid(Integer uid);
    
    @Select({
        "select",
        "id, uid, powers, power_group_id",
        "from xxd_user_power"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="powers", property="powers", jdbcType=JdbcType.VARCHAR),
        @Result(column="power_group_id", property="powerGroupId", jdbcType=JdbcType.INTEGER)
    })
    ArrayList<XxdUserPower> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @UpdateProvider(type=XxdUserPowerSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(XxdUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    @Update({
        "update xxd_user_power",
        "set uid = #{uid,jdbcType=INTEGER},",
          "powers = #{powers,jdbcType=VARCHAR},",
          "power_group_id = #{powerGroupId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(XxdUserPower record);
}