package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;
import static org.apache.ibatis.jdbc.SqlBuilder.AND;


import com.xxd.models.XxdUser;

public class XxdUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user
     *
     * @mbggenerated
     */
    public String insertSelective(XxdUser record) {
        BEGIN();
        INSERT_INTO("xxd_user");
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            VALUES("username", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=SMALLINT}");
        }
        
        if (record.getPhonenumber() != null) {
            VALUES("phonenumber", "#{phonenumber,jdbcType=VARCHAR}");
        }
        
        if (record.getIdCard() != null) {
            VALUES("id_card", "#{idCard,jdbcType=VARCHAR}");
        }
        
        if (record.getBankCard() != null) {
            VALUES("bank_card", "#{bankCard,jdbcType=VARCHAR}");
        }
        
        if (record.getBankLocation() != null) {
            VALUES("bank_location", "#{bankLocation,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=SMALLINT}");
        }
        
        if (record.getSalt() != null) {
            VALUES("salt", "#{salt,jdbcType=VARCHAR}");
        }
        
        if(record.getIs_able() != null) {
        	VALUES("is_able", "#{is_able,jdbcType=SMALLINT}");
        }
        
        if(record.getCreate_time() != null) {
        	VALUES("create_time", "#{create_time,jdbcType=VARCHAR}");
        }
        
        if(record.getParent_id() != null) {
        	VALUES("parent_id", "#{parent_id,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdUser record) {
        BEGIN();
        UPDATE("xxd_user");
        
        if (record.getUsername() != null) {
            SET("username = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=SMALLINT}");
        }
        
        if (record.getPhonenumber() != null) {
            SET("phonenumber = #{phonenumber,jdbcType=VARCHAR}");
        }
        
        if (record.getIdCard() != null) {
            SET("id_card = #{idCard,jdbcType=VARCHAR}");
        }
        
        if (record.getBankCard() != null) {
            SET("bank_card = #{bankCard,jdbcType=VARCHAR}");
        }
        
        if (record.getBankLocation() != null) {
            SET("bank_location = #{bankLocation,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=SMALLINT}");
        }
        
        if (record.getSalt() != null) {
            SET("salt = #{salt,jdbcType=VARCHAR}");
        }
        
        if(record.getIs_able() != null) {
        	SET("is_able = #{is_able,jdbcType=VARCHAR}");
        }
        
        if(record.getParent_id() != null) {
        	SET("parent_id = #{parent_id,jdbcType=INTEGER}");
        }
        
        if(record.getName() != null) {
        	SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        WHERE("uid = #{uid,jdbcType=INTEGER}");
        
        return SQL();
    }
}