package com.xxd.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.xxd.models.XxdUserPower;

public class XxdUserPowerSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    public String insertSelective(XxdUserPower record) {
        BEGIN();
        INSERT_INTO("xxd_user_power");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getPowers() != null) {
            VALUES("powers", "#{powers,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerGroupId() != null) {
            VALUES("power_group_id", "#{powerGroupId,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxd_user_power
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(XxdUserPower record) {
        BEGIN();
        UPDATE("xxd_user_power");
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getPowers() != null) {
            SET("powers = #{powers,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerGroupId() != null) {
            SET("power_group_id = #{powerGroupId,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}