package com.xxd.models;

import java.math.BigDecimal;

/**
 * 购物订单
 * @author Liang
 * @version 1.0
 */

public class XxdBuyOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.addr_id
     *
     * @mbggenerated
     */
    private Integer addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.freight_id
     *
     * @mbggenerated
     */
    private Integer freightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.buy_id
     *
     * @mbggenerated
     */
    private Integer buyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_buy_order.sta
     *
     * @mbggenerated
     */
    private Short sta;
    
    
    private String staCon;
    
    /**
     * 订单状态（1为待支付；2为支付成功，待发货；3为支付失败；4为已发货，待收货；5为已收货，订单完成）
     */
    private Short type;
    
    public XxdBuyOrder() {}
    
    public XxdBuyOrder(Integer buy_id, Short type) {
    	setBuyId(buy_id);
    	setType(type);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.id
     *
     * @return the value of xxd_buy_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.id
     *
     * @param id the value for xxd_buy_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.time
     *
     * @return the value of xxd_buy_order.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.time
     *
     * @param time the value for xxd_buy_order.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.total_price
     *
     * @return the value of xxd_buy_order.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.total_price
     *
     * @param totalPrice the value for xxd_buy_order.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.addr_id
     *
     * @return the value of xxd_buy_order.addr_id
     *
     * @mbggenerated
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.addr_id
     *
     * @param addrId the value for xxd_buy_order.addr_id
     *
     * @mbggenerated
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.freight_id
     *
     * @return the value of xxd_buy_order.freight_id
     *
     * @mbggenerated
     */
    public Integer getFreightId() {
        return freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.freight_id
     *
     * @param freightId the value for xxd_buy_order.freight_id
     *
     * @mbggenerated
     */
    public void setFreightId(Integer freightId) {
        this.freightId = freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.order_id
     *
     * @return the value of xxd_buy_order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.order_id
     *
     * @param orderId the value for xxd_buy_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.buy_id
     *
     * @return the value of xxd_buy_order.buy_id
     *
     * @mbggenerated
     */
    public Integer getBuyId() {
        return buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.buy_id
     *
     * @param buyId the value for xxd_buy_order.buy_id
     *
     * @mbggenerated
     */
    public void setBuyId(Integer buyId) {
        this.buyId = buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_buy_order.sta
     *
     * @return the value of xxd_buy_order.sta
     *
     * @mbggenerated
     */
    public Short getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_buy_order.sta
     *
     * @param sta the value for xxd_buy_order.sta
     *
     * @mbggenerated
     */
    public void setSta(Short sta) {
        this.sta = sta;
    }

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public String getStaCon() {
		return staCon;
	}

	public void setStaCon(String staCon) {
		this.staCon = staCon;
	}
}