package com.xxd.models;

/**
 * 用户投诉信息
 * @author Liang
 * @version 1.0
 */

public class XxdComplain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.complain_uid
     *
     * @mbggenerated
     */
    private Integer complainUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.reason
     *
     * @mbggenerated
     */
    private Short reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.save_dir
     *
     * @mbggenerated
     */
    private String saveDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.sta
     *
     * @mbggenerated
     */
    private Short sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.result_desc
     *
     * @mbggenerated
     */
    private String resultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_complain.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.id
     *
     * @return the value of xxd_complain.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.id
     *
     * @param id the value for xxd_complain.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.uid
     *
     * @return the value of xxd_complain.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.uid
     *
     * @param uid the value for xxd_complain.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.complain_uid
     *
     * @return the value of xxd_complain.complain_uid
     *
     * @mbggenerated
     */
    public Integer getComplainUid() {
        return complainUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.complain_uid
     *
     * @param complainUid the value for xxd_complain.complain_uid
     *
     * @mbggenerated
     */
    public void setComplainUid(Integer complainUid) {
        this.complainUid = complainUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.reason
     *
     * @return the value of xxd_complain.reason
     *
     * @mbggenerated
     */
    public Short getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.reason
     *
     * @param reason the value for xxd_complain.reason
     *
     * @mbggenerated
     */
    public void setReason(Short reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.save_dir
     *
     * @return the value of xxd_complain.save_dir
     *
     * @mbggenerated
     */
    public String getSaveDir() {
        return saveDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.save_dir
     *
     * @param saveDir the value for xxd_complain.save_dir
     *
     * @mbggenerated
     */
    public void setSaveDir(String saveDir) {
        this.saveDir = saveDir == null ? null : saveDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.sta
     *
     * @return the value of xxd_complain.sta
     *
     * @mbggenerated
     */
    public Short getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.sta
     *
     * @param sta the value for xxd_complain.sta
     *
     * @mbggenerated
     */
    public void setSta(Short sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.result_desc
     *
     * @return the value of xxd_complain.result_desc
     *
     * @mbggenerated
     */
    public String getResultDesc() {
        return resultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.result_desc
     *
     * @param resultDesc the value for xxd_complain.result_desc
     *
     * @mbggenerated
     */
    public void setResultDesc(String resultDesc) {
        this.resultDesc = resultDesc == null ? null : resultDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_complain.time
     *
     * @return the value of xxd_complain.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_complain.time
     *
     * @param time the value for xxd_complain.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}