package com.xxd.models;

import java.math.BigDecimal;

/**
 * 提现订单
 * @author Liang
 * @version 1.0
 */

public class XxdCashOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_cash_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_cash_order.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_cash_order.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_cash_order.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * 提现状态（需要总管理员审核，然后线下转账。1为待审核；2为审核通过，准许提现；3为审核不通过，拒绝提现）
     */
    private Short sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_cash_order.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.id
     *
     * @return the value of xxd_cash_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.id
     *
     * @param id the value for xxd_cash_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.uid
     *
     * @return the value of xxd_cash_order.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.uid
     *
     * @param uid the value for xxd_cash_order.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.time
     *
     * @return the value of xxd_cash_order.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.time
     *
     * @param time the value for xxd_cash_order.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.price
     *
     * @return the value of xxd_cash_order.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.price
     *
     * @param price the value for xxd_cash_order.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.sta
     *
     * @return the value of xxd_cash_order.sta
     *
     * @mbggenerated
     */
    public Short getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.sta
     *
     * @param sta the value for xxd_cash_order.sta
     *
     * @mbggenerated
     */
    public void setSta(Short sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_cash_order.fail_reason
     *
     * @return the value of xxd_cash_order.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_cash_order.fail_reason
     *
     * @param failReason the value for xxd_cash_order.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }
}