package com.xxd.models;

public class XxdGoodsGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_num
     *
     * @mbggenerated
     */
    private Short groupNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_start_time
     *
     * @mbggenerated
     */
    private String groupStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_end_time
     *
     * @mbggenerated
     */
    private String groupEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_sta
     *
     * @mbggenerated
     */
    private Short groupSta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_vaild_time
     *
     * @mbggenerated
     */
    private Short groupVaildTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_times
     *
     * @mbggenerated
     */
    private Integer groupTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_picture
     *
     * @mbggenerated
     */
    private String groupPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_group.group_title
     *
     * @mbggenerated
     */
    private String groupTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.id
     *
     * @return the value of xxd_goods_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.id
     *
     * @param id the value for xxd_goods_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.goods_id
     *
     * @return the value of xxd_goods_group.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.goods_id
     *
     * @param goodsId the value for xxd_goods_group.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_num
     *
     * @return the value of xxd_goods_group.group_num
     *
     * @mbggenerated
     */
    public Short getGroupNum() {
        return groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_num
     *
     * @param groupNum the value for xxd_goods_group.group_num
     *
     * @mbggenerated
     */
    public void setGroupNum(Short groupNum) {
        this.groupNum = groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_start_time
     *
     * @return the value of xxd_goods_group.group_start_time
     *
     * @mbggenerated
     */
    public String getGroupStartTime() {
        return groupStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_start_time
     *
     * @param groupStartTime the value for xxd_goods_group.group_start_time
     *
     * @mbggenerated
     */
    public void setGroupStartTime(String groupStartTime) {
        this.groupStartTime = groupStartTime == null ? null : groupStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_end_time
     *
     * @return the value of xxd_goods_group.group_end_time
     *
     * @mbggenerated
     */
    public String getGroupEndTime() {
        return groupEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_end_time
     *
     * @param groupEndTime the value for xxd_goods_group.group_end_time
     *
     * @mbggenerated
     */
    public void setGroupEndTime(String groupEndTime) {
        this.groupEndTime = groupEndTime == null ? null : groupEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_sta
     *
     * @return the value of xxd_goods_group.group_sta
     *
     * @mbggenerated
     */
    public Short getGroupSta() {
        return groupSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_sta
     *
     * @param groupSta the value for xxd_goods_group.group_sta
     *
     * @mbggenerated
     */
    public void setGroupSta(Short groupSta) {
        this.groupSta = groupSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_vaild_time
     *
     * @return the value of xxd_goods_group.group_vaild_time
     *
     * @mbggenerated
     */
    public Short getGroupVaildTime() {
        return groupVaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_vaild_time
     *
     * @param groupVaildTime the value for xxd_goods_group.group_vaild_time
     *
     * @mbggenerated
     */
    public void setGroupVaildTime(Short groupVaildTime) {
        this.groupVaildTime = groupVaildTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_times
     *
     * @return the value of xxd_goods_group.group_times
     *
     * @mbggenerated
     */
    public Integer getGroupTimes() {
        return groupTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_times
     *
     * @param groupTimes the value for xxd_goods_group.group_times
     *
     * @mbggenerated
     */
    public void setGroupTimes(Integer groupTimes) {
        this.groupTimes = groupTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.time
     *
     * @return the value of xxd_goods_group.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.time
     *
     * @param time the value for xxd_goods_group.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_picture
     *
     * @return the value of xxd_goods_group.group_picture
     *
     * @mbggenerated
     */
    public String getGroupPicture() {
        return groupPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_picture
     *
     * @param groupPicture the value for xxd_goods_group.group_picture
     *
     * @mbggenerated
     */
    public void setGroupPicture(String groupPicture) {
        this.groupPicture = groupPicture == null ? null : groupPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_group.group_title
     *
     * @return the value of xxd_goods_group.group_title
     *
     * @mbggenerated
     */
    public String getGroupTitle() {
        return groupTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_group.group_title
     *
     * @param groupTitle the value for xxd_goods_group.group_title
     *
     * @mbggenerated
     */
    public void setGroupTitle(String groupTitle) {
        this.groupTitle = groupTitle == null ? null : groupTitle.trim();
    }

	@Override
	public String toString() {
		return "XxdGoodsGroup [id=" + id + ", goodsId=" + goodsId + ", groupNum=" + groupNum + ", groupStartTime="
				+ groupStartTime + ", groupEndTime=" + groupEndTime + ", groupSta=" + groupSta + ", groupVaildTime="
				+ groupVaildTime + ", groupTimes=" + groupTimes + ", time=" + time + ", groupPicture=" + groupPicture
				+ ", groupTitle=" + groupTitle + "]";
	}
    
}