package com.xxd.models;

public class XxdGoodsParametric {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_parametric.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_parametric.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_parametric.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_parametric.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_parametric.sort_no
     *
     * @mbggenerated
     */
    private Short sortNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_parametric.id
     *
     * @return the value of xxd_goods_parametric.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_parametric.id
     *
     * @param id the value for xxd_goods_parametric.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_parametric.name
     *
     * @return the value of xxd_goods_parametric.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_parametric.name
     *
     * @param name the value for xxd_goods_parametric.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_parametric.value
     *
     * @return the value of xxd_goods_parametric.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_parametric.value
     *
     * @param value the value for xxd_goods_parametric.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_parametric.goods_id
     *
     * @return the value of xxd_goods_parametric.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_parametric.goods_id
     *
     * @param goodsId the value for xxd_goods_parametric.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_parametric.sort_no
     *
     * @return the value of xxd_goods_parametric.sort_no
     *
     * @mbggenerated
     */
    public Short getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_parametric.sort_no
     *
     * @param sortNo the value for xxd_goods_parametric.sort_no
     *
     * @mbggenerated
     */
    public void setSortNo(Short sortNo) {
        this.sortNo = sortNo;
    }
}