package com.xxd.models;

/**
 * 商品分类信息
 * @author Liang
 * @version 1.0
 */

public class XxdGoodsClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_class.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_class.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_class.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_class.level
     *
     * @mbggenerated
     */
    private Short level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_class.id
     *
     * @return the value of xxd_goods_class.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_class.id
     *
     * @param id the value for xxd_goods_class.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_class.name
     *
     * @return the value of xxd_goods_class.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_class.name
     *
     * @param name the value for xxd_goods_class.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_class.parent_id
     *
     * @return the value of xxd_goods_class.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_class.parent_id
     *
     * @param parentId the value for xxd_goods_class.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_class.level
     *
     * @return the value of xxd_goods_class.level
     *
     * @mbggenerated
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_class.level
     *
     * @param level the value for xxd_goods_class.level
     *
     * @mbggenerated
     */
    public void setLevel(Short level) {
        this.level = level;
    }
}