package com.xxd.models;

import java.math.BigDecimal;

public class XxdGoodsProductPackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.send_position
     *
     * @mbggenerated
     */
    private String sendPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.img_font_dir
     *
     * @mbggenerated
     */
    private String imgFontDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.show_img_dir
     *
     * @mbggenerated
     */
    private String showImgDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.ownership_leader_id
     *
     * @mbggenerated
     */
    private Integer ownershipLeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.grounding_sta
     *
     * @mbggenerated
     */
    private Short groundingSta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods_product_package.class_id
     *
     * @mbggenerated
     */
    private Integer classId;
    
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.id
     *
     * @return the value of xxd_goods_product_package.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.id
     *
     * @param id the value for xxd_goods_product_package.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.name
     *
     * @return the value of xxd_goods_product_package.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.name
     *
     * @param name the value for xxd_goods_product_package.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.market_price
     *
     * @return the value of xxd_goods_product_package.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.market_price
     *
     * @param marketPrice the value for xxd_goods_product_package.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.price
     *
     * @return the value of xxd_goods_product_package.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.price
     *
     * @param price the value for xxd_goods_product_package.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.num
     *
     * @return the value of xxd_goods_product_package.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.num
     *
     * @param num the value for xxd_goods_product_package.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.send_position
     *
     * @return the value of xxd_goods_product_package.send_position
     *
     * @mbggenerated
     */
    public String getSendPosition() {
        return sendPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.send_position
     *
     * @param sendPosition the value for xxd_goods_product_package.send_position
     *
     * @mbggenerated
     */
    public void setSendPosition(String sendPosition) {
        this.sendPosition = sendPosition == null ? null : sendPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.img_font_dir
     *
     * @return the value of xxd_goods_product_package.img_font_dir
     *
     * @mbggenerated
     */
    public String getImgFontDir() {
        return imgFontDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.img_font_dir
     *
     * @param imgFontDir the value for xxd_goods_product_package.img_font_dir
     *
     * @mbggenerated
     */
    public void setImgFontDir(String imgFontDir) {
        this.imgFontDir = imgFontDir == null ? null : imgFontDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.show_img_dir
     *
     * @return the value of xxd_goods_product_package.show_img_dir
     *
     * @mbggenerated
     */
    public String getShowImgDir() {
        return showImgDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.show_img_dir
     *
     * @param showImgDir the value for xxd_goods_product_package.show_img_dir
     *
     * @mbggenerated
     */
    public void setShowImgDir(String showImgDir) {
        this.showImgDir = showImgDir == null ? null : showImgDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.ownership_leader_id
     *
     * @return the value of xxd_goods_product_package.ownership_leader_id
     *
     * @mbggenerated
     */
    public Integer getOwnershipLeaderId() {
        return ownershipLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.ownership_leader_id
     *
     * @param ownershipLeaderId the value for xxd_goods_product_package.ownership_leader_id
     *
     * @mbggenerated
     */
    public void setOwnershipLeaderId(Integer ownershipLeaderId) {
        this.ownershipLeaderId = ownershipLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.grounding_sta
     *
     * @return the value of xxd_goods_product_package.grounding_sta
     *
     * @mbggenerated
     */
    public Short getGroundingSta() {
        return groundingSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.grounding_sta
     *
     * @param groundingSta the value for xxd_goods_product_package.grounding_sta
     *
     * @mbggenerated
     */
    public void setGroundingSta(Short groundingSta) {
        this.groundingSta = groundingSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.type
     *
     * @return the value of xxd_goods_product_package.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.type
     *
     * @param type the value for xxd_goods_product_package.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods_product_package.class_id
     *
     * @return the value of xxd_goods_product_package.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods_product_package.class_id
     *
     * @param classId the value for xxd_goods_product_package.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}
}