package com.xxd.models;

import java.math.BigDecimal;

/**
 * 商品信息
 * @author Liang
 * @version 1.0
 */

public class XxdGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.id
     *
     * @mbggenerated
     */
    private Integer id;
    
    private Integer transferId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.market_price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.member_price
     *
     * @mbggenerated
     */
    private BigDecimal memberPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.leader_price
     *
     * @mbggenerated
     */
    private BigDecimal leaderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.send_position
     *
     * @mbggenerated
     */
    private String sendPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.img_font_dir
     *
     * @mbggenerated
     */
    private String imgFontDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.show_img_dir
     *
     * @mbggenerated
     */
    private String showImgDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.ownership_leader_id
     *
     * @mbggenerated
     */
    private Integer ownershipLeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_goods.grounding_sta
     *
     * @mbggenerated
     */
    private Short groundingSta;
    
    /**
     * 商品类型（1为自有商品，2为团导商品）
     */
    private Short type;
    
    private Integer classId;
    
    private String className;
    
    private Integer siImg;
    
    private Integer ifImg;
    
    private String saveDir;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.id
     *
     * @return the value of xxd_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.id
     *
     * @param id the value for xxd_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.name
     *
     * @return the value of xxd_goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.name
     *
     * @param name the value for xxd_goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.market_price
     *
     * @return the value of xxd_goods.market_price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.market_price
     *
     * @param marketPrice the value for xxd_goods.market_price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.member_price
     *
     * @return the value of xxd_goods.member_price
     *
     * @mbggenerated
     */
    public BigDecimal getMemberPrice() {
        return memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.member_price
     *
     * @param memberPrice the value for xxd_goods.member_price
     *
     * @mbggenerated
     */
    public void setMemberPrice(BigDecimal memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.leader_price
     *
     * @return the value of xxd_goods.leader_price
     *
     * @mbggenerated
     */
    public BigDecimal getLeaderPrice() {
        return leaderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.leader_price
     *
     * @param leaderPrice the value for xxd_goods.leader_price
     *
     * @mbggenerated
     */
    public void setLeaderPrice(BigDecimal leaderPrice) {
        this.leaderPrice = leaderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.num
     *
     * @return the value of xxd_goods.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.num
     *
     * @param num the value for xxd_goods.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.send_position
     *
     * @return the value of xxd_goods.send_position
     *
     * @mbggenerated
     */
    public String getSendPosition() {
        return sendPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.send_position
     *
     * @param sendPosition the value for xxd_goods.send_position
     *
     * @mbggenerated
     */
    public void setSendPosition(String sendPosition) {
        this.sendPosition = sendPosition == null ? null : sendPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.img_font_dir
     *
     * @return the value of xxd_goods.img_font_dir
     *
     * @mbggenerated
     */
    public String getImgFontDir() {
        return imgFontDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.img_font_dir
     *
     * @param imgFontDir the value for xxd_goods.img_font_dir
     *
     * @mbggenerated
     */
    public void setImgFontDir(String imgFontDir) {
        this.imgFontDir = imgFontDir == null ? null : imgFontDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.show_img_dir
     *
     * @return the value of xxd_goods.show_img_dir
     *
     * @mbggenerated
     */
    public String getShowImgDir() {
        return showImgDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.show_img_dir
     *
     * @param showImgDir the value for xxd_goods.show_img_dir
     *
     * @mbggenerated
     */
    public void setShowImgDir(String showImgDir) {
        this.showImgDir = showImgDir == null ? null : showImgDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.ownership_leader_id
     *
     * @return the value of xxd_goods.ownership_leader_id
     *
     * @mbggenerated
     */
    public Integer getOwnershipLeaderId() {
        return ownershipLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.ownership_leader_id
     *
     * @param ownershipLeaderId the value for xxd_goods.ownership_leader_id
     *
     * @mbggenerated
     */
    public void setOwnershipLeaderId(Integer ownershipLeaderId) {
        this.ownershipLeaderId = ownershipLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_goods.grounding_sta
     *
     * @return the value of xxd_goods.grounding_sta
     *
     * @mbggenerated
     */
    public Short getGroundingSta() {
        return groundingSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_goods.grounding_sta
     *
     * @param groundingSta the value for xxd_goods.grounding_sta
     *
     * @mbggenerated
     */
    public void setGroundingSta(Short groundingSta) {
        this.groundingSta = groundingSta;
    }

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Integer getClassId() {
		return classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public final Integer getSiImg() {
		return siImg;
	}

	public final void setSiImg(Integer siImg) {
		this.siImg = siImg;
	}

	public final Integer getIfImg() {
		return ifImg;
	}

	public final void setIfImg(Integer ifImg) {
		this.ifImg = ifImg;
	}

	public final String getSaveDir() {
		return saveDir;
	}

	public final void setSaveDir(String saveDir) {
		this.saveDir = saveDir;
	}

	public final Integer getTransferId() {
		return transferId;
	}

	public final void setTransferId(Integer transferId) {
		this.transferId = transferId;
	}

}