package com.xxd.models;

public class XxdHopeBuy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_hope_buy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_hope_buy.contents
     *
     * @mbggenerated
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_hope_buy.goodsImg
     *
     * @mbggenerated
     */
    private String goodsimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_hope_buy.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_hope_buy.id
     *
     * @return the value of xxd_hope_buy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_hope_buy.id
     *
     * @param id the value for xxd_hope_buy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_hope_buy.contents
     *
     * @return the value of xxd_hope_buy.contents
     *
     * @mbggenerated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_hope_buy.contents
     *
     * @param contents the value for xxd_hope_buy.contents
     *
     * @mbggenerated
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_hope_buy.goodsImg
     *
     * @return the value of xxd_hope_buy.goodsImg
     *
     * @mbggenerated
     */
    public String getGoodsimg() {
        return goodsimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_hope_buy.goodsImg
     *
     * @param goodsimg the value for xxd_hope_buy.goodsImg
     *
     * @mbggenerated
     */
    public void setGoodsimg(String goodsimg) {
        this.goodsimg = goodsimg == null ? null : goodsimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_hope_buy.uid
     *
     * @return the value of xxd_hope_buy.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_hope_buy.uid
     *
     * @param uid the value for xxd_hope_buy.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}