package com.xxd.models;

import java.math.BigDecimal;

/**
 * 用户积分表格
 * @author Liang
 * @version 1.0
 */

public class XxdIntegration {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration.integration
     *
     * @mbggenerated
     */
    private BigDecimal integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration.abled
     *
     * @mbggenerated
     */
    private BigDecimal abled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration.disabled
     *
     * @mbggenerated
     */
    private BigDecimal disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration.id
     *
     * @return the value of xxd_integration.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration.id
     *
     * @param id the value for xxd_integration.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration.uid
     *
     * @return the value of xxd_integration.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration.uid
     *
     * @param uid the value for xxd_integration.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration.integration
     *
     * @return the value of xxd_integration.integration
     *
     * @mbggenerated
     */
    public BigDecimal getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration.integration
     *
     * @param integration the value for xxd_integration.integration
     *
     * @mbggenerated
     */
    public void setIntegration(BigDecimal integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration.abled
     *
     * @return the value of xxd_integration.abled
     *
     * @mbggenerated
     */
    public BigDecimal getAbled() {
        return abled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration.abled
     *
     * @param abled the value for xxd_integration.abled
     *
     * @mbggenerated
     */
    public void setAbled(BigDecimal abled) {
        this.abled = abled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration.disabled
     *
     * @return the value of xxd_integration.disabled
     *
     * @mbggenerated
     */
    public BigDecimal getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration.disabled
     *
     * @param disabled the value for xxd_integration.disabled
     *
     * @mbggenerated
     */
    public void setDisabled(BigDecimal disabled) {
        this.disabled = disabled;
    }
    
}