package com.xxd.models;

/**
 * 用户消费积分记录
 * @author Liang
 * @version 1.0
 */

public class XxdIntegrationRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_record.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_record.integration_num
     *
     * @mbggenerated
     */
    private String integrationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_record.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_record.contact_id
     *
     * @mbggenerated
     */
    private Integer contactId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_record.id
     *
     * @return the value of xxd_integration_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_record.id
     *
     * @param id the value for xxd_integration_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_record.time
     *
     * @return the value of xxd_integration_record.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_record.time
     *
     * @param time the value for xxd_integration_record.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_record.integration_num
     *
     * @return the value of xxd_integration_record.integration_num
     *
     * @mbggenerated
     */
    public String getIntegrationNum() {
        return integrationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_record.integration_num
     *
     * @param integrationNum the value for xxd_integration_record.integration_num
     *
     * @mbggenerated
     */
    public void setIntegrationNum(String integrationNum) {
        this.integrationNum = integrationNum == null ? null : integrationNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_record.type
     *
     * @return the value of xxd_integration_record.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_record.type
     *
     * @param type the value for xxd_integration_record.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_record.contact_id
     *
     * @return the value of xxd_integration_record.contact_id
     *
     * @mbggenerated
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_record.contact_id
     *
     * @param contactId the value for xxd_integration_record.contact_id
     *
     * @mbggenerated
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
}