package com.xxd.models;

import java.math.BigDecimal;

/**
 * 用户积分交易信息
 * @author Liang
 * @version 1.0
 */

public class XxdIntegrationTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.integration
     *
     * @mbggenerated
     */
    private BigDecimal integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.from_id
     *
     * @mbggenerated
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.to_id
     *
     * @mbggenerated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_transfer.transfer_type
     *
     * @mbggenerated
     */
    private Short transferType;
    
    private String transferTypeCon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.id
     *
     * @return the value of xxd_integration_transfer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.id
     *
     * @param id the value for xxd_integration_transfer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.integration
     *
     * @return the value of xxd_integration_transfer.integration
     *
     * @mbggenerated
     */
    public BigDecimal getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.integration
     *
     * @param integration the value for xxd_integration_transfer.integration
     *
     * @mbggenerated
     */
    public void setIntegration(BigDecimal integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.time
     *
     * @return the value of xxd_integration_transfer.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.time
     *
     * @param time the value for xxd_integration_transfer.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.from_id
     *
     * @return the value of xxd_integration_transfer.from_id
     *
     * @mbggenerated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.from_id
     *
     * @param fromId the value for xxd_integration_transfer.from_id
     *
     * @mbggenerated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.to_id
     *
     * @return the value of xxd_integration_transfer.to_id
     *
     * @mbggenerated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.to_id
     *
     * @param toId the value for xxd_integration_transfer.to_id
     *
     * @mbggenerated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_transfer.transfer_type
     *
     * @return the value of xxd_integration_transfer.transfer_type
     *
     * @mbggenerated
     */
    public Short getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_transfer.transfer_type
     *
     * @param transferType the value for xxd_integration_transfer.transfer_type
     *
     * @mbggenerated
     */
    public void setTransferType(Short transferType) {
        this.transferType = transferType;
    }

	public String getTransferTypeCon() {
		return transferTypeCon;
	}

	public void setTransferTypeCon(String transferTypeCon) {
		this.transferTypeCon = transferTypeCon;
	}
}