package com.xxd.models;

import java.math.BigDecimal;

/**
 * 用户购买积分记录
 * @author Liang
 * @version 1.0
 */

public class XxdIntegrationBuyRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_buy_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_buy_record.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_buy_record.integration
     *
     * @mbggenerated
     */
    private BigDecimal integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_integration_buy_record.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_buy_record.id
     *
     * @return the value of xxd_integration_buy_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_buy_record.id
     *
     * @param id the value for xxd_integration_buy_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_buy_record.uid
     *
     * @return the value of xxd_integration_buy_record.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_buy_record.uid
     *
     * @param uid the value for xxd_integration_buy_record.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_buy_record.integration
     *
     * @return the value of xxd_integration_buy_record.integration
     *
     * @mbggenerated
     */
    public BigDecimal getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_buy_record.integration
     *
     * @param integration the value for xxd_integration_buy_record.integration
     *
     * @mbggenerated
     */
    public void setIntegration(BigDecimal integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_integration_buy_record.time
     *
     * @return the value of xxd_integration_buy_record.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_integration_buy_record.time
     *
     * @param time the value for xxd_integration_buy_record.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}