package com.xxd.models;

/**
 * 订单寄货单信息
 * @author Liang
 * @version 1.0
 */

public class XxdOrderExpressNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_order_express_no.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_order_express_no.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_order_express_no.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_order_express_no.order_user_id
     *
     * @mbggenerated
     */
    private Integer orderUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_order_express_no.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_order_express_no.id
     *
     * @return the value of xxd_order_express_no.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_order_express_no.id
     *
     * @param id the value for xxd_order_express_no.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_order_express_no.order_id
     *
     * @return the value of xxd_order_express_no.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_order_express_no.order_id
     *
     * @param orderId the value for xxd_order_express_no.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_order_express_no.order_no
     *
     * @return the value of xxd_order_express_no.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_order_express_no.order_no
     *
     * @param orderNo the value for xxd_order_express_no.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_order_express_no.order_user_id
     *
     * @return the value of xxd_order_express_no.order_user_id
     *
     * @mbggenerated
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_order_express_no.order_user_id
     *
     * @param orderUserId the value for xxd_order_express_no.order_user_id
     *
     * @mbggenerated
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_order_express_no.time
     *
     * @return the value of xxd_order_express_no.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_order_express_no.time
     *
     * @param time the value for xxd_order_express_no.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}