package com.xxd.models;

/**
 * 用户权限列表
 * @author Liang
 * @version 1.0
 */

public class XxdPowerGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.is_abled
     *
     * @mbggenerated
     */
    private Short isAbled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.powers
     *
     * @mbggenerated
     */
    private String powers;
    
    private String powersCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.create_uid
     *
     * @mbggenerated
     */
    private Integer createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power_group.create_time
     *
     * @mbggenerated
     */
    private String createTime;
    
    private String power_outline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.id
     *
     * @return the value of xxd_power_group.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.id
     *
     * @param id the value for xxd_power_group.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.name
     *
     * @return the value of xxd_power_group.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.name
     *
     * @param name the value for xxd_power_group.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.is_abled
     *
     * @return the value of xxd_power_group.is_abled
     *
     * @mbggenerated
     */
    public Short getIsAbled() {
        return isAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.is_abled
     *
     * @param isAbled the value for xxd_power_group.is_abled
     *
     * @mbggenerated
     */
    public void setIsAbled(Short isAbled) {
        this.isAbled = isAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.powers
     *
     * @return the value of xxd_power_group.powers
     *
     * @mbggenerated
     */
    public String getPowers() {
        return powers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.powers
     *
     * @param powers the value for xxd_power_group.powers
     *
     * @mbggenerated
     */
    public void setPowers(String powers) {
        this.powers = powers == null ? null : powers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.create_uid
     *
     * @return the value of xxd_power_group.create_uid
     *
     * @mbggenerated
     */
    public Integer getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.create_uid
     *
     * @param createUid the value for xxd_power_group.create_uid
     *
     * @mbggenerated
     */
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power_group.create_time
     *
     * @return the value of xxd_power_group.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power_group.create_time
     *
     * @param createTime the value for xxd_power_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

	public String getPower_outline() {
		return power_outline;
	}

	public void setPower_outline(String power_outline) {
		this.power_outline = power_outline;
	}

	public String getPowersCon() {
		return powersCon;
	}

	public void setPowersCon(String powersCon) {
		this.powersCon = powersCon;
	}
}