package com.xxd.models;

public class XxdPictureHandle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_picture_handle.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_picture_handle.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_picture_handle.good_name
     *
     * @mbggenerated
     */
    private String goodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_picture_handle.handle_time
     *
     * @mbggenerated
     */
    private String handleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_picture_handle.save_dir
     *
     * @mbggenerated
     */
    private String saveDir;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_picture_handle.id
     *
     * @return the value of xxd_picture_handle.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_picture_handle.id
     *
     * @param id the value for xxd_picture_handle.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_picture_handle.url
     *
     * @return the value of xxd_picture_handle.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_picture_handle.url
     *
     * @param url the value for xxd_picture_handle.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_picture_handle.good_name
     *
     * @return the value of xxd_picture_handle.good_name
     *
     * @mbggenerated
     */
    public String getGoodName() {
        return goodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_picture_handle.good_name
     *
     * @param goodName the value for xxd_picture_handle.good_name
     *
     * @mbggenerated
     */
    public void setGoodName(String goodName) {
        this.goodName = goodName == null ? null : goodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_picture_handle.handle_time
     *
     * @return the value of xxd_picture_handle.handle_time
     *
     * @mbggenerated
     */
    public String getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_picture_handle.handle_time
     *
     * @param handleTime the value for xxd_picture_handle.handle_time
     *
     * @mbggenerated
     */
    public void setHandleTime(String handleTime) {
        this.handleTime = handleTime == null ? null : handleTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_picture_handle.save_dir
     *
     * @return the value of xxd_picture_handle.save_dir
     *
     * @mbggenerated
     */
    public String getSaveDir() {
        return saveDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_picture_handle.save_dir
     *
     * @param saveDir the value for xxd_picture_handle.save_dir
     *
     * @mbggenerated
     */
    public void setSaveDir(String saveDir) {
        this.saveDir = saveDir == null ? null : saveDir.trim();
    }
}