package com.xxd.models;

/**
 * 权限
 * @author Liang
 * @version 1.0
 */

public class XxdPower {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power.outline
     *
     * @mbggenerated
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power.type
     *
     * @mbggenerated
     */
    private Short type;
    
    private String typeCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power.is_abled
     *
     * @mbggenerated
     */
    private Short isAbled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_power.details
     *
     * @mbggenerated
     */
    private String details;
    
    private Integer parent_id;
    
    private Short isChecked;
    
    private String uri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power.id
     *
     * @return the value of xxd_power.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power.id
     *
     * @param id the value for xxd_power.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power.outline
     *
     * @return the value of xxd_power.outline
     *
     * @mbggenerated
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power.outline
     *
     * @param outline the value for xxd_power.outline
     *
     * @mbggenerated
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power.type
     *
     * @return the value of xxd_power.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power.type
     *
     * @param type the value for xxd_power.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power.is_abled
     *
     * @return the value of xxd_power.is_abled
     *
     * @mbggenerated
     */
    public Short getIsAbled() {
        return isAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power.is_abled
     *
     * @param isAbled the value for xxd_power.is_abled
     *
     * @mbggenerated
     */
    public void setIsAbled(Short isAbled) {
        this.isAbled = isAbled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_power.details
     *
     * @return the value of xxd_power.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_power.details
     *
     * @param details the value for xxd_power.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

	public Integer getParent_id() {
		return parent_id;
	}

	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	public String getTypeCon() {
		return typeCon;
	}

	public void setTypeCon(String typeCon) {
		this.typeCon = typeCon;
	}

	public Short getIsChecked() {
		return isChecked;
	}

	public void setIsChecked(Short isChecked) {
		this.isChecked = isChecked;
	}

	public String getUri() {
		return uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}
}