package com.xxd.models;

/**
 * 用户建议
 * @author Liang
 * @version 1.0
 */

public class XxdSuggestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.save_dir
     *
     * @mbggenerated
     */
    private String saveDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.is_read
     *
     * @mbggenerated
     */
    private Short isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_suggestion.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.id
     *
     * @return the value of xxd_suggestion.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.id
     *
     * @param id the value for xxd_suggestion.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.time
     *
     * @return the value of xxd_suggestion.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.time
     *
     * @param time the value for xxd_suggestion.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.content
     *
     * @return the value of xxd_suggestion.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.content
     *
     * @param content the value for xxd_suggestion.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.save_dir
     *
     * @return the value of xxd_suggestion.save_dir
     *
     * @mbggenerated
     */
    public String getSaveDir() {
        return saveDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.save_dir
     *
     * @param saveDir the value for xxd_suggestion.save_dir
     *
     * @mbggenerated
     */
    public void setSaveDir(String saveDir) {
        this.saveDir = saveDir == null ? null : saveDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.is_read
     *
     * @return the value of xxd_suggestion.is_read
     *
     * @mbggenerated
     */
    public Short getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.is_read
     *
     * @param isRead the value for xxd_suggestion.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Short isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_suggestion.uid
     *
     * @return the value of xxd_suggestion.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_suggestion.uid
     *
     * @param uid the value for xxd_suggestion.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}