package com.xxd.models;

import java.math.BigDecimal;

/**
 * 用户信息
 * @author Liang
 * @version 1.0
 */

public class XxdUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.sex
     *
     * @mbggenerated
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.phonenumber
     *
     * @mbggenerated
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.bank_card
     *
     * @mbggenerated
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.bank_location
     *
     * @mbggenerated
     */
    private String bankLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.type
     *
     * @mbggenerated
     */
    private Short type;
    
    private String typeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user.salt
     *
     * @mbggenerated
     */
    private String salt;
    
    private Short is_able;
    
    private String create_time;
    
    private Integer parent_id;
    
    private String name;
    
    private Short leader_level;
    
    private String parentUsername;
    
    private String parentName;
    
    public XxdUser() {}
    
    public XxdUser(Integer uid, Short type) {
    	setUid(uid);
    	setType(type);
    }
    
    public XxdUser(Integer uid, Short type, Integer parent_id) {
    	setUid(uid);
    	setType(type);
    	setParent_id(parent_id);
    }
    
    public XxdUser(Short type, Integer parent_id) {
    	setType(type);
    	setParent_id(parent_id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.uid
     *
     * @return the value of xxd_user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.uid
     *
     * @param uid the value for xxd_user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.username
     *
     * @return the value of xxd_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.username
     *
     * @param username the value for xxd_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.password
     *
     * @return the value of xxd_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.password
     *
     * @param password the value for xxd_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.sex
     *
     * @return the value of xxd_user.sex
     *
     * @mbggenerated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.sex
     *
     * @param sex the value for xxd_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.phonenumber
     *
     * @return the value of xxd_user.phonenumber
     *
     * @mbggenerated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.phonenumber
     *
     * @param phonenumber the value for xxd_user.phonenumber
     *
     * @mbggenerated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.id_card
     *
     * @return the value of xxd_user.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.id_card
     *
     * @param idCard the value for xxd_user.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.bank_card
     *
     * @return the value of xxd_user.bank_card
     *
     * @mbggenerated
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.bank_card
     *
     * @param bankCard the value for xxd_user.bank_card
     *
     * @mbggenerated
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.bank_location
     *
     * @return the value of xxd_user.bank_location
     *
     * @mbggenerated
     */
    public String getBankLocation() {
        return bankLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.bank_location
     *
     * @param bankLocation the value for xxd_user.bank_location
     *
     * @mbggenerated
     */
    public void setBankLocation(String bankLocation) {
        this.bankLocation = bankLocation == null ? null : bankLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.type
     *
     * @return the value of xxd_user.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.type
     *
     * @param type the value for xxd_user.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    public String getTypeStr() {
		return typeStr;
	}

	public void setTypeStr(String typeStr) {
		this.typeStr = typeStr;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user.salt
     *
     * @return the value of xxd_user.salt
     *
     * @mbggenerated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user.salt
     *
     * @param salt the value for xxd_user.salt
     *
     * @mbggenerated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

	public Short getIs_able() {
		return is_able;
	}

	public void setIs_able(Short is_able) {
		this.is_able = is_able;
	}

	public String getCreate_time() {
		return create_time;
	}

	public void setCreate_time(String create_time) {
		this.create_time = create_time;
	}

	public Integer getParent_id() {
		return parent_id;
	}

	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	public String getParentUsername() {
		return parentUsername;
	}

	public void setParentUsername(String parentUsername) {
		this.parentUsername = parentUsername;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getLeader_level() {
		return leader_level;
	}

	public void setLeader_level(Short leader_level) {
		this.leader_level = leader_level;
	}
}