package com.xxd.models;

/**
 * 用户收货地址信息
 * @author Liang
 * @version 1.0
 */

public class XxdUserAddr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.addr_details
     *
     * @mbggenerated
     */
    private String addrDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_addr.is_first
     *
     * @mbggenerated
     */
    private Short isFirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.id
     *
     * @return the value of xxd_user_addr.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.id
     *
     * @param id the value for xxd_user_addr.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.phone
     *
     * @return the value of xxd_user_addr.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.phone
     *
     * @param phone the value for xxd_user_addr.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.name
     *
     * @return the value of xxd_user_addr.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.name
     *
     * @param name the value for xxd_user_addr.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.telephone
     *
     * @return the value of xxd_user_addr.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.telephone
     *
     * @param telephone the value for xxd_user_addr.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.addr
     *
     * @return the value of xxd_user_addr.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.addr
     *
     * @param addr the value for xxd_user_addr.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.addr_details
     *
     * @return the value of xxd_user_addr.addr_details
     *
     * @mbggenerated
     */
    public String getAddrDetails() {
        return addrDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.addr_details
     *
     * @param addrDetails the value for xxd_user_addr.addr_details
     *
     * @mbggenerated
     */
    public void setAddrDetails(String addrDetails) {
        this.addrDetails = addrDetails == null ? null : addrDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.tags
     *
     * @return the value of xxd_user_addr.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.tags
     *
     * @param tags the value for xxd_user_addr.tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.remark
     *
     * @return the value of xxd_user_addr.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.remark
     *
     * @param remark the value for xxd_user_addr.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.uid
     *
     * @return the value of xxd_user_addr.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.uid
     *
     * @param uid the value for xxd_user_addr.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_addr.is_first
     *
     * @return the value of xxd_user_addr.is_first
     *
     * @mbggenerated
     */
    public Short getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_addr.is_first
     *
     * @param isFirst the value for xxd_user_addr.is_first
     *
     * @mbggenerated
     */
    public void setIsFirst(Short isFirst) {
        this.isFirst = isFirst;
    }
}