package com.xxd.models;

/**
 * 用户全新啊关系表格
 * @author Liang
 * @version 1.0
 */

public class XxdUserPower {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_power.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_power.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_power.powers
     *
     * @mbggenerated
     */
    private String powers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxd_user_power.power_group_id
     *
     * @mbggenerated
     */
    private Integer powerGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_power.id
     *
     * @return the value of xxd_user_power.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_power.id
     *
     * @param id the value for xxd_user_power.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_power.uid
     *
     * @return the value of xxd_user_power.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_power.uid
     *
     * @param uid the value for xxd_user_power.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_power.powers
     *
     * @return the value of xxd_user_power.powers
     *
     * @mbggenerated
     */
    public String getPowers() {
        return powers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_power.powers
     *
     * @param powers the value for xxd_user_power.powers
     *
     * @mbggenerated
     */
    public void setPowers(String powers) {
        this.powers = powers == null ? null : powers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xxd_user_power.power_group_id
     *
     * @return the value of xxd_user_power.power_group_id
     *
     * @mbggenerated
     */
    public Integer getPowerGroupId() {
        return powerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xxd_user_power.power_group_id
     *
     * @param powerGroupId the value for xxd_user_power.power_group_id
     *
     * @mbggenerated
     */
    public void setPowerGroupId(Integer powerGroupId) {
        this.powerGroupId = powerGroupId;
    }
}